### PR TITLE
upgraded to 5.4.1 and made it rootless

### PR DESCRIPTION
**Pull request by takov751**

### CODE REVIEW

**Comment by swichers-xx** [comment]
Have you had any luck getting these cards working on ROCm 5.6 or higher?  I have a rig with 8 RX580's that I have been trying to get running for weeks...

Good work!

**Comment by Firstbober** [comment]
> Have you had any luck getting these cards working on ROCm 5.6 or higher? I have a rig with 8 RX580's that I have been trying to get running for weeks...
> 
> Good work!

AMD abandoned RX580 (gfx803) on ROCm-4.0. There is one person that I know of that still tries to make newer versions work, but they're stuck on 5.4.1.

**Comment by takov751** [comment]
Yes . I even sold my rx580, because using rocm caused some hardware issues

**Comment by swichers-xx** [comment]
Thanks much! I'm gonna give this guy's build a shot! They seem to be at 5.4.3:
https://github.com/tsl0922/pytorch-gfx803/releases

**Pull request closed without merging**
